#define X exit
enum{I=128,N,B,F,L,W,U,E,Q};typedef struct{int t,v;char*s;}T;typedef struct A A;struct A{int k,o;char*s;A*x,*y,*z,*n;};typedef struct H H;char*s;int q;T tk;char*k[]={"if","elif","else","while","func","true","false"};int v[]={F,L,L,W,U,B,B};void nt(){for(;;){if(!s[q]){tk=(T){Q,0,0};return;}int c=s[q];if(isspace(c)){q++;continue;}if(isdigit(c)){int k=0;while(s[q]&&isdigit(s[q]))k=k*10+s[q++]-48;tk=(T){N,k,0};return;}if(isalpha(c)||c=='_'){int b=q++;while(s[q]&&(isalnum(s[q])||s[q]=='_'))q++;char*d=strndup(s+b,q-b);int t=I;for(int j=0;j<7;j++)if(!strcmp(d,k[j])){t=v[j];if(t==B){tk=(T){B,j==5,0};return;}tk=(T){t,0,d};return;}tk=(T){t,0,d};return;}int d=s[q+1];if(c=='='&&d=='='){tk=(T){E,0,0};q+=2;return;}if((c=='&'&&d=='&')||(c=='|'&&d=='|')){tk=(T){c,0,0};q+=2;return;}tk=(T){c,0,0};q++;return;}}
#define is(x) (tk.t==(x))
T ad(){T t=tk;nt();return t;}
#define ex(t) if(!is(t))X(1);nt()
#define PR(t)(t=='|'?1:t=='&'?2:(t==E?3:(t=='<'||t=='>'?4:(t=='+'||t=='-'?5:(t=='*'||t=='%'||t=='/'?6:0)))))
A*na(int k){A*p=calloc(1,sizeof*p);p->k=k;return p;}A*P(),*S(),*K();A*P0(){if(is('(')){ad();A*r=P();ex(')');return r;}if(is(U)){ad();ex('(');A*ps=NULL,**pp=&ps;if(!is(')'))do{if(!is(I))X(1);T t=ad();A*q=na(I);q->s=t.s;A*n=na(',');n->x=q;*pp=n;pp=&n->y;}while(is(',')&&ad().t);ex(')');ex('=');ex('>');A*f=na(U);f->y=ps;f->x=is('{')?K():P();return f;}if(is(N)){A*r=na(N);r->o=ad().v;return r;}if(is(B)){A*r=na(B);r->o=ad().v;return r;}if(is(I)){T t=ad();A*r=na(I);r->s=t.s;if(is('(')){ad();A*as=NULL,**ap=&as;if(!is(')'))do{A*e=P();A*n=na(',');n->x=e;*ap=n;ap=&n->y;}while(is(',')&&ad().t);ex(')');A*c=na('(');c->x=r;c->y=as;return c;}return r;}X(1);}A*J(){if(is('!')||is('-')){int t=ad().t;A*r=na('u');r->o=t;r->x=J();return r;}return P0();}A*B1(int m,A*l){for(;;){int t=tk.t,p=PR(t);if(p<m)break;ad();A*r=J();if(PR(tk.t)>p)r=B1(p+1,r);A*n=na('b');n->o=t;n->x=l;n->y=r;l=n;}return l;}A*P(){return B1(1,J());}A*K(){ex('{');A*h=NULL,**p=&h;while(!is('}')){*p=S();p=&(*p)->n;}ex('}');return h;}A*If(){ex('(');A*c=P();ex(')');A*t=K();A*e=NULL;if(is(L)){ad();if(is(F)){ad();e=If();}else if(is('('))e=If();else e=K();}A*n=na(F);n->x=c;n->y=t;n->z=e;return n;}A*S(){if(is(I)&&(!strcmp(tk.s,"var")||!strcmp(tk.s,"const"))){ad();T t=ad();ex('=');A*e=P();ex(';');A*n=na('v');n->s=t.s;n->x=e;return n;}if(is(I)){int p=q;while(s[p]&&isspace(s[p]))p++;if(s[p]=='='){T t=ad();ad();A*e=P();ex(';');A*n=na('=');n->s=t.s;n->x=e;return n;}}if(is(F)){ad();return If();}if(is(W)){ad();ex('(');A*c=P();ex(')');A*b=K();A*n=na(W);n->x=c;n->y=b;return n;}if(is('{'))return K();A*e=P();ex(';');return e;}typedef struct{int i;A*f;H*e;}V;typedef struct H{char*n;V v;H*next,*up;}H;
#define VN(x) (V){x,0}
#define VB(b) (V){-(b)-1,0}
#define TV(v) (v.i<0?-v.i-1:v.i)
H*ne(H*p){H*e=calloc(1,sizeof*e);e->up=p;return e;}H*fd(H*e,char*s){for(;e;e=e->up)for(H*n=e;n;n=n->next)if(n->n&&!strcmp(n->n,s))return n;return NULL;}void df(H*e,char*s,V v){H*n=malloc(sizeof*n);n->n=s;n->v=v;n->next=e->next;e->next=n;}void as(H*e,char*s,V v){H*n=fd(e,s);if(!n)X(1);n->v=v;}V gv(H*e,char*s){H*n=fd(e,s);if(!n)X(1);return n->v;}V vf(A*f,H*e){return (V){0,f,e};}V ev(A*,H*);V blk(A*s,H*e){V r=VN(0);for(;s;s=s->n)r=ev(s,e);return r;}V ev(A*a,H*e){switch(a?a->k:-1){case N:return VN(a->o);case B:return VB(a->o);case I:return gv(e,a->s);case 'v':{V v=ev(a->x,e);df(e,a->s,v);return v;}case '=':{V v=ev(a->x,e);as(e,a->s,v);return v;}case 'u':{V v=ev(a->x,e);return a->o=='-'?VN(-v.i):VB(!TV(v));}case 'b':{int o=a->o;V l=ev(a->x,e);if(o=='&'){if(!TV(l))return VB(0);V r=ev(a->y,e);return VB(TV(r));}if(o=='|'){if(TV(l))return VB(1);V r=ev(a->y,e);return VB(TV(r));}V r=ev(a->y,e);switch(o){case '+':return VN(l.i+r.i);case '-':return VN(l.i-r.i);case '*':return VN(l.i*r.i);case '/':if(!r.i)X(1);return VN(l.i/r.i);case '%':if(!r.i)X(1);return VN(l.i%r.i);case '<':return VB(l.i<r.i);case '>':return VB(l.i>r.i);case E:return VB(!l.f&&!r.f&&l.i==r.i);}X(1);}case F:return TV(ev(a->x,e))?blk(a->y,e):(a->z?blk(a->z,e):VB(0));case W:{V r=VN(0);for(;TV(ev(a->x,e));)r=blk(a->y,e);return r;}case U:return vf(a,e);case '(':{V f=ev(a->x,e);if(f.f==(A*)1){V v=a->y?ev(a->y->x,e):VN(0);if(v.i<0)puts(v.i==-1?"false":"true");else printf("%d\n",v.i);return VB(1);}A*fn=f.f;H*ce=ne(f.e);A*p=fn->y,*g=a->y;for(;p&&g;p=p->y,g=g->y)df(ce,p->x->s,ev(g->x,e));return blk(fn->x,ce);}}}
