#define X exit
#define R return
enum{I,N,B,F,L,W,U,E,Q};typedef struct{int t,v;char*s;}T;typedef struct A{int k,o;char*s;struct A*x,*y,*z,*n;}A;typedef struct H H;char*s;int q;T t;typedef struct{unsigned char h,t;}Y;unsigned char h(const char*p){unsigned char r=0,l=0;while(*p){l++;r=r*173+*p++;}R r^l;}Y y[]={{89,F},{212,L},{149,L},{100,W},{208,U},{56,B},{134,B},{214,'&'},{74,'|'},{116,E},{61,'<'},{63,'>'},{43,'*'},{47,'.'},{60,'='},{42,'+'},{44,'-'},{46,'/'},{36,'%'},{32,'!'},{41,'('},{40,')'},{122,'{'},{124,'}'},{253,';'},{45,','},{102,'V'},{146,'V'}};int lh(unsigned char h){for(int i=0;i<28;i++)if(y[i].h==h){t.t=y[i].t;t.v=(t.t==B&&h==56);R 1;}R 0;}void n(){for(;;){if(!s[q]){t=(T){Q};R;}int c=s[q];if(isspace(c)){q++;continue;}if(isdigit(c)){int k=0;while(isdigit(s[q]))k=k*10+s[q++]-48;t=(T){N,k};R;}if(isalpha(c)||c=='_'){int b=q++;while(s[q]&&(isalnum(s[q])||s[q]=='_'))q++;char*d=strndup(s+b,q-b);if(lh(h(d))){free(d);R;}t=(T){I,0,d};R;}char b[3]={s[q],s[q+1],0};if((b[0]=='&'&&b[1]=='&')||(b[0]=='|'&&b[1]=='|')||(b[0]=='='&&b[1]=='='))if(lh(h(b))){q+=2;R;}b[1]=0;if(lh(h(b))){q++;R;}t=(T){c};q++;R;}}
#define is(x)(t.t==(x))
T ad(){T u=t;n();R u;}
#define ex(t)if(!is(t))X(1);n()
#define PR(t)(t=='|'?1:t=='&'?2:(t==E?3:(t=='<'||t=='>'?4:(t=='+'||t=='-'?5:(t=='*'||t=='%'||t=='/'?6:0)))))
A*na(int k){A*p=calloc(1,sizeof*p);p->k=k;R p;}A*P(),*S(),*K();A*P0(){if(is('(')){ad();A*r=P();ex(')');R r;}if(is(U)){ad();ex('(');A*ps=NULL,**pp=&ps;if(!is(')'))do{if(!is(I))X(1);T u=ad();A*q=na(I);q->s=u.s;A*n=na(',');n->x=q;*pp=n;pp=&n->y;}while(is(',')&&ad().t);ex(')');ex('=');ex('>');A*f=na(U);f->y=ps;f->x=is('{')?K():P();R f;}if(is(N)){A*r=na(N);r->o=ad().v;R r;}if(is(B)){A*r=na(B);r->o=ad().v;R r;}if(is(I)){T u=ad();A*r=na(I);r->s=u.s;if(is('(')){ad();A*as=NULL,**ap=&as;if(!is(')'))do{A*e=P();A*n=na(',');n->x=e;*ap=n;ap=&n->y;}while(is(',')&&ad().t);ex(')');A*c=na('(');c->x=r;c->y=as;R c;}R r;}X(1);}A*J(){if(is('!')||is('-')){int o=ad().t;A*r=na('u');r->o=o;r->x=J();R r;}R P0();}A*B1(int m,A*l){for(;;){int o=t.t,p=PR(o);if(p<m)break;ad();A*r=J();if(PR(t.t)>p)r=B1(p+1,r);A*n=na('b');n->o=o;n->x=l;n->y=r;l=n;}R l;}A*P(){R B1(1,J());}A*K(){ex('{');A*h=NULL,**p=&h;while(!is('}')){*p=S();p=&(*p)->n;}ex('}');R h;}A*If(){ex('(');A*c=P();ex(')');A*k=K();A*e=NULL;if(is(L)){ad();if(is(F)){ad();e=If();}else if(is('('))e=If();else e=K();}A*n=na(F);n->x=c;n->y=k;n->z=e;R n;}A*S(){if(is('V')){ad();T u=ad();ex('=');A*e=P();ex(';');A*n=na('v');n->s=u.s;n->x=e;R n;}if(is(I)){int p=q;while(isspace(s[p]))p++;if(s[p]=='='){T u=ad();ad();A*e=P();ex(';');A*n=na('=');n->s=u.s;n->x=e;R n;}}if(is(F)){ad();R If();}if(is(W)){ad();ex('(');A*c=P();ex(')');A*b=K();A*n=na(W);n->x=c;n->y=b;R n;}if(is('{'))R K();A*e=P();ex(';');R e;}typedef struct{int i;A*f;H*e;}V;struct H{char*n;V v;struct H*t,*up;};
#define VN(x) (V){x,0,0}
#define VB(b) (V){-(b)-1,0,0}
#define TV(v) (v.i<0?-v.i-1:v.i)
H*ne(H*p){H*e=calloc(1,sizeof*e);e->up=p;R e;}H*fd(H*e,char*s){for(;e;e=e->up)for(H*n=e;n;n=n->t)if(n->n&&!strcmp(n->n,s))R n;R NULL;}void df(H*e,char*s,V v){H*n=malloc(sizeof*n);n->n=s;n->v=v;n->t=e->t;e->t=n;}void as(H*e,char*s,V v){H*n=fd(e,s);if(!n)X(1);n->v=v;}V gv(H*e,char*s){H*n=fd(e,s);if(!n)X(1);R n->v;}V ev(A*,H*);V blk(A*s,H*e){V r=VN(0);for(;s;s=s->n)r=ev(s,e);R r;}V ev(A*a,H*e){switch(a?a->k:-1){case N:R VN(a->o);case B:R VB(a->o);case I:R gv(e,a->s);case 'v':{V v=ev(a->x,e);df(e,a->s,v);R v;}case '=':{V v=ev(a->x,e);as(e,a->s,v);R v;}case 'u':{V v=ev(a->x,e);R a->o=='-'?VN(-v.i):VB(!TV(v));}case 'b':{int o=a->o;V l=ev(a->x,e);if(o=='&'){if(!TV(l))R VB(0);V r=ev(a->y,e);R VB(TV(r));}if(o=='|'){if(TV(l))R VB(1);V r=ev(a->y,e);R VB(TV(r));}V r=ev(a->y,e);switch(o){case '+':R VN(l.i+r.i);case '-':R VN(l.i-r.i);case '*':R VN(l.i*r.i);case '/':if(!r.i)X(1);R VN(l.i/r.i);case '%':if(!r.i)X(1);R VN(l.i%r.i);case '<':R VB(l.i<r.i);case '>':R VB(l.i>r.i);case E:R VB(!l.f&&!r.f&&l.i==r.i);}X(1);}case F:R TV(ev(a->x,e))?blk(a->y,e):(a->z?blk(a->z,e):VB(0));case W:{V r=VN(0);for(;TV(ev(a->x,e));)r=blk(a->y,e);R r;}case U:R (V){0,a,e};case '(':{V f=ev(a->x,e);if(f.f==(A*)1){V v=a->y?ev(a->y->x,e):VN(0);if(v.i<0)puts(v.i==-1?"false":"true");else printf("%d\n",v.i);R VB(1);}A*fn=f.f;H*ce=ne(f.e);A*p=fn->y,*g=a->y;for(;p&&g;p=p->y,g=g->y)df(ce,p->x->s,ev(g->x,e));R blk(fn->x,ce);}}R VB(0);}